version: '3.8'

services:
  laravel:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel-app
    environment:
      - APP_NAME=${ROOT_APP_NAME}
      - APP_ENV=${ROOT_APP_ENV}
      - APP_KEY=${ROOT_APP_KEY}
      - APP_DEBUG=${ROOT_APP_DEBUG}
      - APP_TIMEZONE=${ROOT_APP_TIMEZONE}
      - APP_URL=${ROOT_APP_URL}
      - FRONTEND_URL=${ROOT_FRONTEND_URL}
      - APP_LOCALE=${ROOT_APP_LOCALE}
      - APP_FALLBACK_LOCALE=${ROOT_APP_FALLBACK_LOCALE}
      - APP_FAKER_LOCALE=${ROOT_APP_FAKER_LOCALE}
      - APP_MAINTENANCE_DRIVER=${ROOT_APP_MAINTENANCE_DRIVER}
      #- APP_MAINTENANCE_STORE=${ROOT_APP_MAINTENANCE_STORE}
      - PHP_CLI_SERVER_WORKERS=${ROOT_PHP_CLI_SERVER_WORKERS}
      - BCRYPT_ROUNDS=${ROOT_BCRYPT_ROUNDS}
      - LOG_CHANNEL=${ROOT_LOG_CHANNEL}
      - LOG_STACK=${ROOT_LOG_STACK}
      - LOG_DEPRECATIONS_CHANNEL=${ROOT_LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${ROOT_LOG_LEVEL}
      - DB_CONNECTION=${ROOT_DB_CONNECTION}
      - DB_HOST=${ROOT_DB_HOST}
      - DB_PORT=${ROOT_DB_PORT}
      - DB_DATABASE=${ROOT_DB_DATABASE}
      - DB_USERNAME=${ROOT_DB_USERNAME}
      - DB_PASSWORD=${ROOT_DB_PASSWORD}
      - SESSION_DRIVER=${ROOT_SESSION_DRIVER}
      - SESSION_LIFETIME=${ROOT_SESSION_LIFETIME}
      - SESSION_ENCRYPT=${ROOT_SESSION_ENCRYPT}
      - SESSION_PATH=${ROOT_SESSION_PATH}
      - SESSION_DOMAIN=${ROOT_SESSION_DOMAIN}
      - BROADCAST_CONNECTION=${ROOT_BROADCAST_CONNECTION}
      - FILESYSTEM_DISK=${ROOT_FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${ROOT_QUEUE_CONNECTION}
      - CACHE_STORE=${ROOT_CACHE_STORE}
      - CACHE_PREFIX=${ROOT_CACHE_PREFIX}
      - MEMCACHED_HOST=${ROOT_MEMCACHED_HOST}
      - REDIS_CLIENT=${ROOT_REDIS_CLIENT}
      - REDIS_HOST=${ROOT_REDIS_HOST}
      - REDIS_PASSWORD=${ROOT_REDIS_PASSWORD}
      - REDIS_PORT=${ROOT_REDIS_PORT}
      - MAIL_MAILER=${ROOT_MAIL_MAILER}
      - MAIL_HOST=${ROOT_MAIL_HOST}
      - MAIL_PORT=${ROOT_MAIL_PORT}
      - MAIL_USERNAME=${ROOT_MAIL_USERNAME}
      - MAIL_PASSWORD=${ROOT_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${ROOT_MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${ROOT_MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${ROOT_MAIL_FROM_NAME}
      - AWS_ACCESS_KEY_ID=${ROOT_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${ROOT_AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${ROOT_AWS_DEFAULT_REGION}
      - AWS_BUCKET=${ROOT_AWS_BUCKET}
      - AWS_USE_PATH_STYLE_ENDPOINT=${ROOT_AWS_USE_PATH_STYLE_ENDPOINT}
      - VITE_APP_NAME=${ROOT_VITE_APP_NAME}
    env_file:
      - ./api/.env
    depends_on:
      - mysql
      - redis
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-network

  nuxt:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nuxt-app
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ROOT_MYSQL_DATABASE}
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
