version: '3.8'

services:
  laravel:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_app
    environment:
      - DB_PASSWORD=password
      - DB_DATABASE=laravel
    env_file:
      - ./api/.env
    depends_on:
      - mysql
      - redis
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - '8080:80'
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-network

  nuxt:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_nuxt_app
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
